# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
deploy:
  provider: pypi
  user: manujosephv
  password:
    secure: Hmw7I76iqZkF/a6b1+2z6FL7bLQs/7Zni2ve6PWFne1CTWwfn2itln47PkadhiWg/yFfGAhgF0EX9zeOdvFrngQV7so4dXg1NfAIXtsj4ob4J4v0N5rjwrJCf1XfqZEwVWcmgswoeNgTpzHYLwokyTZEKxAzb6W6HTAlhbzRBR1r0+ol6uGj3wM0mAjb+pKOBytQ8cB8ziD50TTen318+C5xYTVVGMDhYTohgdjJVLnx+sxCRSPnqkcKp67dZSjJt6Jha5EhZc7INdn/3a1uxqsqgJCuQic9Bt/A3ylanB9Y0s/iHn2maPMP2D/noUUNLLmMAaE+etO55q8NnXsg5Dz/5izwDFhynnLZTncl9qUZGhfy1cglIHl6wjIt3yXQclP8bAPy2EYdEGjW6WnT2DbTo39qunNvbAXzvnlVzYiZlD44G4gAahsbHoIvRVusGQV5GVpB60Ab69g7rfJgCg3o/puNw91Xd/XVwCcuQebPfTyipAI3+vWpHjCcH4Hbs39QPPHQgCeim/Rk4RhzXL6XxcOzhGGXNStyUuNIVs8k+Aq95hUZYDwkoC1c0Ij5wP6l44w6jODzj9peKYvGJXK1Fr1sgm/yJEK4rr+36MnQcLsM8j6K8oieHAr4RWDqqjFyMfYI785C0p1pQrxiOhlqu6q4OlNkLPdFayVe1V8=
  on:
    tags: true
  skip_existing: true


