regression: 2458
classification: 763
synthetic_classification_cat_embedding: 3
synthetic_classification_node: 5
synthetic_classification_tabnet: 9
synthetic_classification_node_cat_embed: 3
wand_debug: 4
