target:
- MedHouseVal
continuous_cols:
- AveRooms
- AveBedrms
- Population
- AveOccup
- Latitude
- Longitude
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
categorical_dim: 0
continuous_dim: 6
task: regression
embedding_dims: []
learning_rate: 0.001
loss: MSELoss
metrics:
- mean_squared_error
metrics_params:
- {}
target_range: null
layers: 10-20
batch_norm_continuous_input: true
activation: ReLU
embedding_dropout: 0.5
dropout: 0.5
use_batch_norm: false
initialization: kaiming
_module_src: category_embedding
_model_name: CategoryEmbeddingModel
_config_name: CategoryEmbeddingModelConfig
batch_size: 64
fast_dev_run: true
max_epochs: 3
min_epochs: 1
max_time: null
gpus: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: null
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
checkpoints: null
checkpoints_path: saved_models
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
load_best: true
track_grad_norm: -1
optimizer: Adam
optimizer_params:
  weight_decay: 0
  amsgrad: false
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
output_dim: 1
categorical_cardinality: []
checkpoint_callback: false
